name: Check Code for Programatic or Style Errors

on: push

jobs:
  main:
    name: Setup and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'
      
      - name: Install Pylama
        run: |-
          pip install pylama

      - name: Run Pylama
        run: |-
          pylama ./*.py